language: python
python:
  - "2.7"

install:
  - pip install requests

script:
  # Doesn't matter what the Linode API key is, environment variable just
  # needs to be set.
  - export LINODE_API_KEY='foo'
  - python run_tests.py
