language: python
python:
  - "2.7"

install:
  - pip install requests

script:
  # Doesn't matter that the Linode API key here is, environment variable just
  # needs to be available.
  - export LINODE_API_KEY='foo'
  - python run_tests.py

